matrix:
  include:
  - name: "iOS"
    os: osx
    language: swift
    osx_image: xcode10.1
    before_script: cd iOS/FVM
    script: xcodebuild -project FVM.xcodeproj -scheme FVM -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.1,name=iPhone X' test -configuration Debug ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES 
    after_script: bash  <(curl -s https://codecov.io/bash) -J '^FVM$'
  - name: "Android"
    language: android
    android:
      components:
      - build-tools
      - android
      - extra
      licenses:
      - 'android-.+'
      - 'google-.+'
    before_script: 
    - cd android
    - yes | sdkmanager "build-tools;28.0.3"
    script: ./gradlew test jacocoTestReport
    after_success:
    - cd android
    - bash <(curl -s https://codecov.io/bash)
    - if [ $TRAVIS_BRANCH = "master" ]; then  
      ./gradlew assembleRelease artifactoryPublish -P jFrogUser=$J_FROG_USER -P jFrogPassword=$J_FROG_PASSWORD;
      fi
