matrix:
  include:
  - name: "iOS"
    os: osx
    language: swift
    osx_image: xcode10.1
    before_script: cd iOS/FVM
    script: xcodebuild -scheme FVMTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.1,name=iPhone X' test
  - name: "Android"
    language: android
    jdk: oraclejdk8
    env:
      global:
        - ANDROID_TARGET=android-15
        - ANDROID_ABI=armeabi-v7a
    android:
      components:
      - tools
      - platform-tools
      - extra-android-m2repository
      - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
      - build-tools
      - android
      - extra
      licenses:
      - 'android-.+'
      - 'google-.+'
    before_script: 
    - cd android
    - yes | sdkmanager "build-tools;28.0.3"
    script:
      - ./gradlew build jacocoTestReport assembleAndroidTest
      - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
      - emulator -avd test -no-skin -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
      - ./gradlew connectedCheck
    after_success:
      - bash <(curl -s https://codecov.io/bash)
