matrix:
  include:
  - name: "iOS"
    os: osx
    language: swift
    osx_image: xcode10.1
    before_script: cd iOS/FVM
    script: xcodebuild -scheme FVMTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.1,name=iPhone X' test