matrix:
  include:
  - name: "iOS"
    os: osx
    language: swift
    osx_image: xcode10.1
    before_script: cd iOS/FVM
    script: xcodebuild -scheme FVMTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.1,name=iPhone X' test
  - name: "Android"
    language: android
    android:
      components:
      - build-tools
      - android
      - extra
      licenses:
      - 'android-.+'
      - 'google-.+'
    before_script: 
    - cd android
    - yes | sdkmanager "build-tools;28.0.3"
script: ./gradlew test jacocoTestReport
    after_success: bash <(curl -s https://codecov.io/bash) #Run codecov

allprojects {
  apply plugin: 'jacoco'
}

task codeCoverageReport(type: JacocoReport) {

    // Gather execution data from all subprojects
    // (change this if you e.g. want to calculate unit test/integration test coverage separately)
    executionData fileTree(project.rootDir.absolutePath).include("**/build/jacoco/*.exec")

    // Add all relevant sourcesets from the subprojects
    subprojects.each {
       sourceSets it.sourceSets.main
    }

    reports {
      xml.enabled true
      html.enabled true
      html.destination "${buildDir}/reports/jacoco"
      csv.enabled false
    }
}

// always run the tests before generating the report
codeCoverageReport.dependsOn {
    subprojects*.test
}