matrix:
  include:
  - name: "iOS"
    os: osx
    language: swift
    osx_image: xcode10.1
    before_script: cd iOS/FVM
    script: xcodebuild -scheme FVMTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.1,name=iPhone X' test
  - name: "Android"
    language: android
    android:
      components:
      - build-tools
      - android
      - extra
      licenses:
      - 'android-.+'
      - 'google-.+'
    before_script: 
    - cd android
    - yes | sdkmanager "build-tools;28.0.3"
    script: ./gradlew test
