matrix:
  include:
  - name: "iOS"
    os: osx
    language: swift
    osx_image: xcode10.1
    before_script: cd iOS/VehicleDamageModeling
    script: xcodebuild -scheme VehicleDamageModeling -sdk iphoneos build
    #enable test after migration to scenekit
    #script: xcodebuild -scheme VehicleDamageModelingTests -sdk iphonesimulator test
  - name: "Android"
    language: android
    android:
      components:
      - build-tools-26
      - android-26
      - extra
      licenses:
      - 'android-.+'
      - 'google-.+'
    before_script: cd android
    script: ./gradlew test