language: android
android:
  components:
    - build-tools-26.0.2

    - android-26

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17

script: ./gradlew test jacocoTestReport

before_install:
- pip install --user codecov #Install codecov

after_success: bash <(curl -s https://codecov.io/bash) #Run codecov